### PR TITLE
Fix Validation Errors and Bumpmaps

### LINKED ISSUE #411: Example 06.Meshloaders black objects on DebugMode
## Describe the bug
objects display as all black in Debug Mode.
RenderDoc Capture shows the problem is with the 1024x1024 bumpmap being all black or 0,0 for those objects but they should be all 1,1 (yellow in RG16)

Problem may be with the loaders and the origin may be the recent changes made to the sponza zip file that caused this.

## Steps to Reproduce
Run example 06 on master branch on debug mode
The correct version is rendered in release mode.

You should see something like this

### LINKED ISSUE #472: Fix Threadsafeness of Refcounting on Descriptor Pools and Sets
## Describe the bug
The current design fails to account that a call to `~IGPUDescriptorSet` or `~IDescriptorPool` can come from any thread and we can't impose external synchronization constraints on them.

A similar issue may affect CommandBuffers and CommandPools.

We decided to not tackle that as part of #345 

## Steps to Reproduce
Just think about it.

## Expected vs observed behavior
Destructors should be thread safe, and anything needed to ensure that should propagate to other functions.

However other methods of DescriptorPool and Set should retain their external synchronisation obligation.

## Environment
Everywhere

### PR DESCRIPTION
**Pull request by devshgraphicsprogramming**
## Description

Fixes:
- querying for device properties and limits for extensions that are not supported (dynamic pNext chain construction)
- querying format usages for formats which are not supported (no extension or vulkan instance version)
- not generating mip-maps for images that already have defined mip pyramids (like KTX/DDS)
- only make the mip-pyramid full if there was no mip-pyramid to start with in the first place
- fix #411 
- upstream a bunch of fixes from `ditt` branch
- minor issues with compilation of certain examples

## Testing 

Just running examples, nothing complex like comparing device props and limit structs before and after implementing changes.

## TODO list:

Actually fix #472

### CODE REVIEW

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h [hunk 1]
```diff
@@ -1036,7 +1041,10 @@ auto IGPUObjectFromAssetConverter::create(const asset::ICPUImage** const _begin,
 
         if (needToCompMipsForThisImg(cpuimg))
         {
-            params.usage |= asset::IImage::EUF_TRANSFER_SRC_BIT;
+            params.usage |= asset::IImage::EUF_TRANSFER_SRC_BIT; // this is for blit
+            // I'm already adding usage flags for mip-mapping compute shader
+            params.usage |= asset::IImage::EUF_SAMPLED_BIT; // to read source mips
+            params.usage |= asset::IImage::EUF_STORAGE_BIT; // to write dst mips
```
Comment (devshgraphicsprogramming) [inline include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1047]: am I likely to fuckup the format promotion with this?

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h [hunk 2]
```diff
@@ -1025,8 +1030,8 @@ auto IGPUObjectFromAssetConverter::create(const asset::ICPUImage** const _begin,
         promotionRequest.originalFormat = params.format;
         promotionRequest.usages = {};
 
-        const bool integerFmt = asset::isIntegerFormat(params.format);
-        if (!integerFmt)
+        // override the mip-count if its not an integer format and there was no mip-pyramid specified 
+        if (params.mipLevels==1u && !asset::isIntegerFormat(params.format))
```
Comment (devshgraphicsprogramming) [inline include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1034]: I hope this makes sense @Erfan-Ahmadi

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h [hunk 3]
```diff
@@ -847,12 +847,17 @@ auto IGPUObjectFromAssetConverter::create(const asset::ICPUImage** const _begin,
...
             return false;
         auto format = img->getCreationParameters().format;
         if (asset::isIntegerFormat(format) || asset::isBlockCompressionFormat(format))
             return false;
+        // its enough to define a single mipmap region above the base level to prevent automatic computation
+        for (auto& region : img->getRegions())
+        if (region.imageSubresource.mipLevel)
+            return false;
         return true;
     };
```
Comment (devshgraphicsprogramming) [inline include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:862]: just give this a look @Erfan-Ahmadi

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h (hunk 1 above)
Comment (devshgraphicsprogramming) [reply include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1047]: ok answered my own question with some testing, doing this causes an SRGB image to be promoted to 16bit UNORM

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h [hunk 4]
```diff
@@ -1025,36 +1030,60 @@ auto IGPUObjectFromAssetConverter::create(const asset::ICPUImage** const _begin,
...
+            // but image views with formats that are store-able can be created
+            if (!newFormatIsStorable)
+            {
+                params.flags |= asset::IImage::ECF_MUTABLE_FORMAT_BIT;
+                params.flags |= asset::IImage::ECF_EXTENDED_USAGE_BIT;
+                if (asset::isBlockCompressionFormat(newFormat))
+                    params.flags |= asset::IImage::ECF_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT;
+            }
+        }
+#endif
```
Comment (devshgraphicsprogramming) [inline include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1082]: aaaand it seems we have a blocker @Erfan-Ahmadi

Comment (devshgraphicsprogramming) [reply include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1082]: basically without the list of all the formats we'll use, this will never pass validation :(

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h (hunk 3 above)
Comment (Erfan-Ahmadi) [reply include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:862]: yea it makes sense, althought I would use  `> 0u` instead of treating it like a bool :D

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h (hunk 2 above)
Comment (Erfan-Ahmadi) [reply include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1034]: yea it does

File: include/nbl/video/utilities/IGPUObjectFromAssetConverter.h [hunk 5]
```diff
@@ -1525,20 +1549,55 @@ inline created_gpu_object_array<asset::ICPUImageView> IGPUObjectFromAssetConvert
...
             params.image = (*gpuDeps)[redirs[i]];
-            params.viewType = static_cast<IGPUImageView::E_TYPE>(cpuparams.viewType);
-            params.format = params.image->getCreationParameters().format;
-            memcpy(&params.components, &cpuparams.components, sizeof(params.components));
-            params.subresourceRange = cpuparams.subresourceRange;
-            params.subresourceRange.levelCount = (*gpuDeps)[redirs[i]]->getCreationParameters().mipLevels - params.subresourceRange.baseMipLevel;
+            const auto& gpuImgParams = params.image->getCreationParameters();
+            // override the view's format if the source image got promoted, a bit crude, but don't want to scratch my head about how to promote the views and guess semantics
+            const bool formatGotPromoted = asset::getFormatClass(cpuParams.format)!=asset::getFormatClass(gpuImgParams.format);
+            params.format = formatGotPromoted ? gpuImgParams.format:cpuParams.format;
```
Comment (devshgraphicsprogramming) [inline include/nbl/video/utilities/IGPUObjectFromAssetConverter.h:1568]: @Erfan-Ahmadi corrected the thing that would wipe away all views' formats when using Asset Converter

File: include/nbl/asset/filters/CBlitImageFilter.h [hunk 6]
```diff
@@ -541,10 +552,10 @@ class CBlitImageFilter : public CImageFilter<CBlitImageFilter<Swizzle,Dither,Nor
 									continue;
 
 								auto sample = lineBuffer+i*MaxChannels;
-								value_type swizzledSample[MaxChannels];
+								value_type preSwizzleSample[MaxChannels];
 
 								// TODO: make sure there is no leak due to MaxChannels!
-								base_t::template onDecode(inFormat, state, srcPix, sample, swizzledSample, inBlockCoord.x, inBlockCoord.y);
+								base_t::template onDecode(inFormat, state, srcPix, preSwizzleSample, sample, inBlockCoord.x, inBlockCoord.y);
```
Comment (devshgraphicsprogramming) [inline include/nbl/asset/filters/CBlitImageFilter.h:558]: @achalpandeyy before the `swizzledSample` wouldn't get used at all which would mess with Derivative Map from Heightmap generation
